# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15U-Qpaj4rHBkRMkkDbcuL8H-livxoI4f
"""

# IMPORTACIÓN DE LIBRERÍAS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, Markdown

# CONFIGURACIÓN VISUAL
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (8, 4)

# ==========================================
# FASE 1: ENTENDIMIENTO DEL NEGOCIO
# ==========================================
display(Markdown("""
# Evaluación Procesual: Proyecto de Predicción de Anemia Infantil (La Caza del Problema)
**Integrantes:** Cristopher Fabricio Flores Tinta, Inés Belén Quispe Vallejos, Fabiola, Luz Daniela, Kenneth, Diego

## FASE 1: Entendimiento del Negocio

**1. Objetivo de Negocio:**
Reducir la incidencia de la anemia infantil en menores de 36 meses priorizando la detección temprana. El modelo apoyará la decisión de a quién priorizar para tamizaje de sangre y suplementación de hierro.

**2. Métrica Principal (KPI):**
Tasa de Prevalencia de Anemia Infantil (TPAI).
*   **Qué mide:** La proporción de niños evaluados que son diagnosticados con anemia.
*   **Unidad de medida:** Porcentaje (%).

**3. Definición y cálculo de la métrica:**
*   Fórmula: `(Casos Positivos de Anemia / Total de Niños Evaluados) * 100`
*   Condición clínica: Hemoglobina < 11.0 g/dL = Anemia (Positivo).

**4. Mejora Tentativa:**
Reducir la TPAI del valor actual a un 25% tras el primer año de implementación del modelo predictivo, optimizando los recursos médicos.
"""))

# ==========================================
# FASE 2: ENTENDIMIENTO DE LOS DATOS (EDA)
# ==========================================
display(Markdown("""
## FASE 2: Entendimiento de los Datos (EDA)

### 1. ¿Qué datos tengo?
Utilizamos una base de datos clínica simulada (calibrada con estadísticas reales de ENDSA/EDSA en Bolivia). La unidad de análisis es el niño/paciente. A continuación, cargamos los datos y vemos su estructura:
"""))

# Carga de datos (el encabezado real comienza en la fila 4, por lo que usamos header=3)
df = pd.read_excel('anemia infantil datos.xlsx', header=3)
print(f"Número de registros: {df.shape[0]}")
print(f"Número de variables: {df.shape[1]}\n")
df.info()

display(Markdown("### 2. Cálculo de la Métrica Principal (TPAI Actual / Baseline)"))
# Definición de la variable objetivo
df['Presencia_Anemia'] = np.where(df['Hemoglobina_g_dL'] < 11.0, 1, 0)

# Cálculo de la métrica (Porcentaje)
tpai_actual = df['Presencia_Anemia'].value_counts(normalize=True) * 100
print("--- Tasa de Prevalencia de Anemia Infantil (Baseline) ---")
print(f"Niños sin anemia (0): {tpai_actual[0]:.2f}%")
print(f"Niños con anemia (1): {tpai_actual[1]:.2f}%")


display(Markdown("### 3. ¿Hay datos faltantes y duplicados?"))
faltantes = df.isnull().sum().sum()
duplicados = df.duplicated().sum()
print(f"Total de datos faltantes en todo el dataset: {faltantes}")
print(f"Total de registros duplicados: {duplicados}")
display(Markdown("*Al no haber datos faltantes, la base de datos está 100% completa y no requiere imputación.*"))


display(Markdown("""
### 4. ¿Existen valores atípicos (Outliers)?
Analizamos la variable crítica: el Nivel de Hemoglobina.
**Justificación:** Encontramos valores muy bajos. Sin embargo, **no son errores de digitación**, representan casos reales de anemia severa. No deben ser eliminados porque son las observaciones más importantes para el problema médico.
"""))
plt.figure(figsize=(8, 2))
sns.boxplot(x=df["Hemoglobina_g_dL"], color="lightcoral")
plt.title("Detección de Valores Atípicos en Hemoglobina")
plt.xlabel("Hemoglobina (g/dL)")
plt.show()


display(Markdown("### 5. ¿Cómo se distribuyen los datos?"))
plt.figure(figsize=(8, 4))
sns.histplot(df["Hemoglobina_g_dL"], bins=30, kde=True, color="teal")
plt.axvline(11.0, color='red', linestyle='--', label='Límite Anemia (< 11.0)')
plt.title("Distribución de Niveles de Hemoglobina")
plt.xlabel("Hemoglobina (g/dL)")
plt.ylabel("Frecuencia")
plt.legend()
plt.show()


display(Markdown("### 6. ¿Qué relaciones existen entre variables?"))
cols_numericas = ["Edad_Meses", "Peso_kg", "Talla_cm", "Hemoglobina_g_dL"]
correlaciones = df[cols_numericas].corr()

plt.figure(figsize=(6, 4))
sns.heatmap(correlaciones, annot=True, cmap="Blues", fmt=".2f")
plt.title("Correlación: Variables Físicas vs Clínicas")
plt.show()

# ==========================================
# FASE 3: HALLAZGO INTERESANTE Y CONCLUSIÓN
# ==========================================
display(Markdown("""
## FASE 3: Hallazgo Interesante y Conclusiones

**Hallazgo:**
Como se observa en el mapa de calor, existe una correlación muy fuerte (multicolinealidad) entre la Edad, el Peso y la Talla (crecimiento natural). Sin embargo, **la Hemoglobina tiene una correlación débil (cercana a 0) con el peso y la talla**.

**Importancia para el Negocio:**
Esto nos demuestra que el estado nutricional físico (estar grande o pesado) no garantiza que el niño no tenga anemia. Para predecir la enfermedad, el modelo de Machine Learning no podrá basarse solo en el peso y la talla, sino que deberá aprender obligatoriamente de los determinantes sociales (nivel educativo de la madre, lactancia, suplementos). Esto justifica la necesidad de utilizar un modelo predictivo avanzado de clasificación.
"""))

# ==========================================
# IMPORTACIÓN DE LIBRERÍAS Y CONFIGURACIÓN
# ==========================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from IPython.display import display, Markdown

sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (8, 4)

display(Markdown("""
# Análisis Exploratorio de Datos (EDA) - Minería de Datos
**Objetivos:**
- Comprender el propósito del EDA.
- Detectar problemas de calidad de datos.
- Interpretar distribuciones y relaciones.
- Formular hipótesis de negocio o investigación.
- Aplicar EDA al proyecto de cada grupo.

---
## PARTE 1: EJEMPLOS GUIADOS DE LA CLASE
### Ejemplo guiado: Rendimiento académico
"""))

# EJEMPLO GUIADO: RENDIMIENTO ACADÉMICO
df_guiado = pd.DataFrame({
    "Estudiante": ["A", "B", "C", "D"],
    "Horas_Estudio": [2, 5, 8, 10],
    "Asistencia": [60, 75, 85, 95],
    "Nota": [45, 60, 80, 92]
})
display(df_guiado)
print("\n--- Información del Dataset ---")
df_guiado.info()
print("\n--- Estadísticas Descriptivas ---")
display(df_guiado.describe())

# DATOS FALTANTES
display(Markdown("### Datos Faltantes y Duplicados"))
faltantes = pd.DataFrame({"Edad": [25, np.nan, 27, 30], "Ingreso": [500, 600, np.nan, 850]})
display(faltantes)
print("Faltantes por columna:\n", faltantes.isnull().sum())

# DATOS DUPLICADOS
duplicados = pd.DataFrame({"ID": [1, 2, 2, 3], "Nombre": ["Ana", "Juan", "Juan", "Luis"]})
display(duplicados)
print("Total de duplicados:", duplicados.duplicated().sum())

# VALORES ATÍPICOS (OUTLIERS)
display(Markdown("### Valores atípicos (Outliers)"))
edades = [19, 20, 21, 22, 23, 24, 240]
plt.figure(figsize=(6,3))
plt.boxplot(edades)
plt.title("Detección visual de outliers")
plt.show()

s = pd.Series(edades)
Q1 = s.quantile(0.25)
Q3 = s.quantile(0.75)
IQR = Q3 - Q1
out = s[(s < Q1 - 1.5 * IQR) | (s > Q3 + 1.5 * IQR)]
print("Valor atípico detectado matemáticamente:\n", out)

# DISTRIBUCIONES Y RELACIONES (EJEMPLO GUIADO)
display(Markdown("### Distribuciones y Relaciones"))
plt.figure(figsize=(6,3))
plt.hist(df_guiado["Nota"], bins=5, edgecolor="black", color="skyblue")
plt.title("Distribución de notas")
plt.xlabel("Nota")
plt.ylabel("Frecuencia")
plt.show()

plt.figure(figsize=(6,3))
sns.scatterplot(data=df_guiado, x="Horas_Estudio", y="Nota", s=100, color="orange")
plt.title("Relación Horas de Estudio vs Nota")
plt.show()

plt.figure(figsize=(5,3))
sns.heatmap(df_guiado[["Horas_Estudio", "Asistencia", "Nota"]].corr(numeric_only=True), annot=True, cmap="Blues")
plt.title("Mapa de Calor - Correlaciones")
plt.show()

# DATASET SINTÉTICO MÁS REALISTA
display(Markdown("### Dataset sintético más realista"))
np.random.seed(42)
n = 200
proyecto = pd.DataFrame({
    "Tiempo_Sitio": np.random.normal(40, 10, n),
    "Paginas": np.random.normal(12, 3, n),
    "Compras": np.random.normal(5, 1.5, n),
    "Monto": np.random.normal(80, 20, n)
})
display(proyecto.head())
print("\nNulos en el proyecto sintético:\n", proyecto.isnull().sum())

plt.figure()
sns.heatmap(proyecto.corr(numeric_only=True), annot=True, cmap="viridis")
plt.title("Correlación Dataset Sintético")
plt.show()

display(Markdown("""
---
## PARTE 2: ACTIVIDAD - DETECTIVES DE DATOS (NUESTRO PROYECTO)
**Proyecto:** La Caza del Problema - Anemia Infantil en Bolivia
**Integrantes:** Cristopher Fabricio Flores Tinta, Inés Belén Quispe Vallejos, Fabiola, Luz Daniela, Kenneth, Diego
"""))

# CARGA DE LOS DATOS REALES DEL GRUPO
df_anemia = pd.read_excel('anemia infantil datos.xlsx', header=3)
# Creamos la métrica / variable objetivo
df_anemia['Presencia_Anemia'] = np.where(df_anemia['Hemoglobina_g_dL'] < 11.0, 1, 0)

# MISION 1
display(Markdown("### Misión 1: Entendiendo la estructura"))
print(f"Número de registros: {df_anemia.shape[0]}")
print(f"Número de variables: {df_anemia.shape[1]}")
print("\nTipos de datos:")
print(df_anemia.dtypes)

# MISION 2
display(Markdown("### Misión 2: Calidad de los datos"))
print(f"Faltantes en la base de datos: {df_anemia.isnull().sum().sum()}")
print(f"Duplicados en la base de datos: {df_anemia.duplicated().sum()}")
print("Inconsistencias: No se encontraron. La base está lista para modelar sin imputaciones.")

# MISION 3
display(Markdown("### Misión 3: Atípicos, Distribuciones y Relaciones"))

# 1. Un Outlier
plt.figure(figsize=(8, 2))
sns.boxplot(x=df_anemia["Hemoglobina_g_dL"], color="lightcoral")
plt.title("Detección de Valores Atípicos en Hemoglobina (Casos Severos Reales)")
plt.xlabel("Hemoglobina (g/dL)")
plt.show()

# 2. Una Distribución Interesante
plt.figure(figsize=(8, 4))
sns.histplot(df_anemia["Hemoglobina_g_dL"], bins=30, kde=True, color="teal")
plt.axvline(11.0, color='red', linestyle='--', label='Límite Anemia (< 11.0)')
plt.title("Distribución de Niveles de Hemoglobina")
plt.xlabel("Hemoglobina (g/dL)")
plt.ylabel("Frecuencia")
plt.legend()
plt.show()

# 3. Una Relación Relevante
cols_numericas_anemia = ["Edad_Meses", "Peso_kg", "Talla_cm", "Hemoglobina_g_dL"]
plt.figure(figsize=(6, 4))
sns.heatmap(df_anemia[cols_numericas_anemia].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlación: Variables Físicas vs Clínicas")
plt.show()

# MISION 4
display(Markdown("""
### Misión 4: Hipótesis de Negocio (El Hallazgo Interesante)
* **Hipótesis:** "Creemos que **el factor social/materno** influye en **la presencia de anemia** porque observamos **que la hemoglobina tiene una correlación muy débil con el peso y la talla del niño.**"
* **Justificación:** Estar alto o pesado no garantiza no tener anemia. El modelo de Machine Learning requerirá de las otras variables categóricas (como nivel educativo y lactancia) para predecir correctamente la enfermedad.

---
## MINI EVALUACIÓN (Respuestas del Grupo)
1. **¿Qué información brinda un boxplot?** Muestra la mediana, los cuartiles y ayuda a identificar rápidamente valores atípicos (outliers) mediante los "bigotes".
2. **¿Qué significa una correlación cercana a 1?** Significa que hay una relación lineal positiva perfecta; si una variable sube, la otra también (ej. Edad y Talla).
3. **¿Qué hacer cuando existen valores faltantes?** Se puede imputar (llenar con la media/mediana) o eliminar la fila/columna dependiendo del porcentaje de pérdida. En nuestro caso, ¡tuvimos 0 faltantes!
4. **¿Por qué el EDA se realiza antes del modelado?** Porque si entrenamos un modelo con datos "basura" (ruido, multicolinealidad, outliers incorrectos), el modelo aprenderá mal. *Si no entiendes tus datos, no entiendes tu problema.*
"""))